apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        node-restriction.kubernetes.io/kafka: "true"
      initContainers:
      - name: check-zookeeper
        image: busybox
        command:
        - sh
        - -c
        - |
          until nc -z zookeeper-service.default.svc.cluster.local 2181; do
            echo "Waiting for ZooKeeper to be ready...";
            sleep 3;
          done;
          echo "ZooKeeper is ready.";
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service.default.svc.cluster.local:2181"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://$(MY_POD_IP):9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "Yes"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        ports:
        - containerPort: 9092
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - kafka-broker-api-versions.sh --bootstrap-server localhost:9092
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - name: plaintext
    protocol: TCP
    port: 9092
    targetPort: 9092
  type: ClusterIP
